-- ============================================
-- 自动生成的工作流种子数据
-- 共 151 条
-- ============================================

INSERT INTO workflows (name, slug, description, category, cover_url, video_url, download_path, sort_order)
VALUES
  ('电商宣传视频', 'b2b_video_v1_1', '【更新Seedream 4.0】电商宣传视频', '视频生成', '', '', 'Workflow-B2B_VIDEO_v1_1-draft-5905', 1),
  ('每日英语短文', 'english_words_text_1', '【更新Seedream 4.0】每日英语短文', '教育工具', '', '', 'Workflow-English_words_TEXT_1-draft-4973', 2),
  ('绘画', 'hh', '绘画', '图文生成', '', '', 'Workflow-HH-draft-5441', 3),
  ('数字人-万物对口型图片（唱歌+口播）', 'infinite_tpszr_1', '数字人-万物对口型图片（唱歌+口播）', '视频生成', '', '', 'Workflow-Infinite_tpszr_1-draft-4126', 4),
  ('近代人物传奇一生【一镜到底】（进阶版） 一个视频5000资源点以上  扣子限制失败率有点高，', 'legen_life_video_all_v5_1', '近代人物传奇一生【一镜到底】（进阶版） 一个视频5000资源点以上  扣子限制失败率有点高，', '视频生成', '', '', 'Workflow-Legen_life_video_all_V5_1-draft-5159', 5),
  ('民间灵异怪谈短视频', 'mjgushi_v1_1', '民间灵异怪谈短视频', '视频生成', '', '', 'Workflow-MJgushi_V1_1-draft-3997', 6),
  ('根据抖音或者公众号链接内容一键生成PPT的工作流', 'no16_url_2_aippt_1_1', '根据抖音或者公众号链接内容一键生成PPT的工作流', '图文生成', '', '', 'Workflow-No16_url_2_aippt_1_1-draft-9283', 7),
  ('根据希沃上传题目的格式要求，参考给出的实例题目，进行出题。', 'no1_exampaper_assistant_xiwo_1_1', '根据希沃上传题目的格式要求，参考给出的实例题目，进行出题。', '教育工具', '', '', 'Workflow-No1_ExamPaper_Assistant_xiwo_1_1-draft-6184', 8),
  ('根据希沃上传题目的格式要求，参考给出的实例题目，进行出题。', 'no1_exampaper_assistant_xiwo_1_1-2', '根据希沃上传题目的格式要求，参考给出的实例题目，进行出题。', '教育工具', '', '', 'Workflow-No1_ExamPaper_Assistant_xiwo_1_1-draft-9160', 9),
  ('课题写作助手工作流，输入课题的题目和参考论文，帮你生成课题的申报材料。', 'no20_keti_shenbao_1_1', '课题写作助手工作流，输入课题的题目和参考论文，帮你生成课题的申报材料。', '教育工具', '', '', 'Workflow-No20_keti_shenbao_1_1-draft-9269', 10),
  ('输入诉状，生成律师委托函', 'no22_lawyers_litigation_letter_1_1', '输入诉状，生成律师委托函', '办公效率', '', '', 'Workflow-No22_Lawyers_Litigation_Letter_1_1-draft-9261', 11),
  ('生成每日英语的学习视频', 'no24_everyday_english_1_1', '生成每日英语的学习视频', '视频生成', '', '', 'Workflow-No24_everyday_english_1_1-draft-9256', 12),
  ('AI资讯快报图文', 'no25_ainews_imag_1', 'AI资讯快报图文', '图文生成', '', '', 'Workflow-No25_ainews_imag_1-draft-9251', 13),
  ('根据上传的错题出题。可进行多项选择。', 'no40_math_err2paper_1', '根据上传的错题出题。可进行多项选择。', '教育工具', '', '', 'Workflow-No40_math_err2paper_1-draft-9221', 14),
  ('书法练习助手，讲解汉字的写法注意技巧。', 'no45_shufa_zhushou_1_1', '书法练习助手，讲解汉字的写法注意技巧。', '教育工具', '', '', 'Workflow-No45_shufa_zhushou_1_1-draft-9209', 15),
  ('输入古诗名字，生成剪映草稿视频。', 'no46_gushi_vedio_3_1', '输入古诗名字，生成剪映草稿视频。', '视频生成', '', '', 'Workflow-No46_gushi_vedio_3_1-draft-9204', 16),
  ('图片理解的方案，用户输入某学生的1张语文作文的图片，工作流按照设定的评分标准，对作文进行评分。', 'no4_zuowenpigai_oneimag_1', '图片理解的方案，用户输入某学生的1张语文作文的图片，工作流按照设定的评分标准，对作文进行评分。', '图文生成', '', '', 'Workflow-No4_zuowenpigai_Oneimag_1-draft-9216', 17),
  ('数学老师助手，根据错题，整理知识点，根据错题知识点出题。', 'no50_zuoyepanduan_yansheng_1_1', '数学老师助手，根据错题，整理知识点，根据错题知识点出题。', '教育工具', '', '', 'Workflow-No50_zuoyepanduan_yansheng_1_1-draft-9199', 18),
  ('体育专业饮食图文图谱', 'no53_tiyuyinshi_tupu_1_1', '体育专业饮食图文图谱', '图文生成', '', '', 'Workflow-No53_tiyuyinshi_tupu_1_1-draft-9187', 19),
  ('输入故事名称，一键生成6片段故事绘本，可用于儿童教育。', 'no6_gushihuiben_6duan_1_1', '输入故事名称，一键生成6片段故事绘本，可用于儿童教育。', '视频生成', '', '', 'Workflow-No6_gushihuiben_6duan_1_1-draft-9298', 20),
  ('一键生成爆款大字情感文案', 'qgwa_st_1', '【更新Seedream 4.0】一键生成爆款大字情感文案', '视频生成', '', '', 'Workflow-QGWA_ST_1-draft-5741', 21),
  ('今日语录爆款视频', 'quote_the_day_1', '【更新Seedream 4.0】今日语录爆款视频', '视频生成', '', '', 'Workflow-Quote_the_day_1-draft-5922', 22),
  ('T12图文工作流：历史行业批量出图', 't12lishi', 'T12图文工作流：历史行业批量出图', '视频生成', '', '', 'Workflow-T12lishi-draft-2008', 23),
  ('T12图文工作流：历史行业批量出图', 't12lishi-2', 'T12图文工作流：历史行业批量出图', '视频生成', '', '', 'Workflow-T12lishi-draft-6152', 24),
  ('T12图文工作流：历史行业批量出图', 't12lishi-3', 'T12图文工作流：历史行业批量出图', '视频生成', '', '', 'Workflow-T12lishi-draft-6152 (1)', 25),
  ('T31暖心海报批量出图', 't31nuanxin', 'T31暖心海报批量出图', '图文生成', '', '', 'Workflow-T31nuanxin-draft-4912', 26),
  ('全平台装修室内设计爆款图文', 'xhszxtw_1', '【更新Seedream 4.0】全平台装修室内设计爆款图文', '图文生成', '', '', 'Workflow-XHSZXTW_1-draft-5725', 27),
  ('小红书图文链接文案提取+分析+批量改写+写入飞书【免费插件版】', 'xhstext_feishu_1', '小红书图文链接文案提取+分析+批量改写+写入飞书【免费插件版】', '图文生成', '', '', 'Workflow-XHStext_feishu_1-draft-5595', 28),
  ('阿里云oss存储上传', 'add_oss_video_880624', '阿里云oss存储上传', 'AI工具', '', '', 'Workflow-add_oss_video_880624-draft-4554', 29),
  ('用来处理图片逻辑', 'assess_experiment_photo_1', '用来处理图片逻辑', '图文生成', '', '', 'Workflow-assess_experiment_photo_1-v0.0.2-9744', 30),
  ('爆款轮播书单5.0', 'baokuanlunbo_1', '【更新Seedream 4.0】爆款轮播书单5.0', '视频生成', '', '', 'Workflow-baokuanlunbo_1-draft-4824', 31),
  ('英文版-四格书单工作流', 'book_k_1_1', '【更新Seedream 4.0】英文版-四格书单工作流', '视频生成', '', '', 'Workflow-book_k_1_1-draft-5785', 32),
  ('公众号文章仿写 1、公众号文章提取，信息提炼 2、大模型提示词微调 3、上传文章素材，保存草稿 4、支持分段配图 4、公众号开发者授权方式', 'c1_gzh_rewrite_v2', '公众号文章仿写 1、公众号文章提取，信息提炼 2、大模型提示词微调 3、上传文章素材，保存草稿 4、支持分段配图 4、公众号开发者授权方式', '视频生成', '', '', 'Workflow-c1_gzh_rewrite_v2-draft-6052', 33),
  ('沉浸式历史悬疑故事-最新铜色版', 'chengjinshixuanyigushi_v3_1', '【更新Seedream 4.0】沉浸式历史悬疑故事-最新铜色版', '视频生成', '', '', 'Workflow-chengjinshixuanyigushi_V3_1-draft-4958', 34),
  ('沉浸式历史悬疑故事-最新铜色版', 'chengjinshixuanyigushi_v3_1-2', '【更新Seedream 4.0】沉浸式历史悬疑故事-最新铜色版', '视频生成', '', '', 'Workflow-chengjinshixuanyigushi_V3_1-draft-6013', 35),
  ('奇异历史悬疑故事', 'chengjinshixuanyigushi_v5_1', '奇异历史悬疑故事', '视频生成', '', '', 'Workflow-chengjinshixuanyigushi_V5_1-draft-4103', 36),
  ('老黄历解说-V3', 'chinese_alm_v3_1', '【更新Seedream 4.0】老黄历解说-V3', '视频生成', '', '', 'Workflow-chinese_alm_v3_1-draft-5971', 37),
  ('电商带货视频', 'daihuo_video_1_1', '电商带货视频', '视频生成', '', '', 'Workflow-daihuo_video_1_1-draft-4416', 38),
  ('一秒记住一个单词', 'danci_v1_2', '一秒记住一个单词', '视频生成', '', '', 'Workflow-danci_V1_2-draft-4048', 39),
  ('一键生成道教玄学视频', 'daojiaoxuanxue_video_1', '【更新Seedream 4.0】一键生成道教玄学视频', '视频生成', '', '', 'Workflow-daojiaoxuanxue_video_1-draft-6203', 40),
  ('电商换脸工作流', 'dianshang_huanlian_1', '电商换脸工作流', '电商工具', '', '', 'Workflow-dianshang_huanlian_1-draft-4163', 41),
  ('韩式漫画认知,书单,心理学,商业类', 'dongman_xlx_1', '【更新Seedream 4.0】韩式漫画认知,书单,心理学,商业类', '视频生成', '', '', 'Workflow-dongman_xlx_1-draft-4670', 42),
  ('抖音文案-短视频获取-并转写成小红书', 'douyinwenan_zhuan_xiaohongshu', '抖音文案-短视频获取-并转写成小红书', '视频生成', '', '', 'Workflow-douyinwenan_zhuan_xiaohongshu-draft-2421', 43),
  ('多人辩论', 'duorenbianlun_2', '多人辩论', 'AI工具', '', '', 'Workflow-duorenbianlun_2-draft-5135', 44),
  ('反拐防骗工作流动态', 'fanguai_dongtai_1', '【更新Seedream 4.0】反拐防骗工作流动态', 'AI工具', '', '', 'Workflow-fanguai_dongtai_1-draft-5254', 45),
  ('反拐防骗工作流', 'fanguai_tuwen_1', '【更新Seedream 4.0】反拐防骗工作流', 'AI工具', '', '', 'Workflow-fanguai_tuwen_1-draft-5269', 46),
  ('每天认识一种花，植物科谱视频-静态', 'flower_sp_v1_2_1_1', '【更新Seedream 4.0】每天认识一种花，植物科谱视频-静态', '视频生成', '', '', 'Workflow-flower_sp_v1_2_1_1-draft-5029', 47),
  ('每天认识一种花，植物科谱视频-静态', 'flower_sp_v1_2_1_1-2', '【更新Seedream 4.0】每天认识一种花，植物科谱视频-静态', '视频生成', '', '', 'Workflow-flower_sp_v1_2_1_1-draft-5045', 48),
  ('公众号输入主题自动生成图文', 'gongzhonghaotuwen_1', '公众号输入主题自动生成图文', '图文生成', '', '', 'Workflow-gongzhonghaotuwen_1-draft-4833', 49),
  ('民间故事', 'guishihui_1', '【更新Seedream 4.0】民间故事', '视频生成', '', '', 'Workflow-guishihui_1-draft-5801', 50),
  ('国风自定义文案工作流', 'guofeng_wenan_1', '【更新Seedream 4.0】国风自定义文案工作流', '图文生成', '', '', 'Workflow-guofeng_wenan_1-draft-4922', 51),
  ('古诗词-唐诗300首  --官方节点版本 ', 'gushici_v2_2_1', '【更新Seedream 4.0】古诗词-唐诗300首  --官方节点版本 ', '视频生成', '', '', 'Workflow-gushici_V2_2_1-draft-6184', 52),
  ('古诗词鉴赏新版', 'gushici_jianshang_1', '【更新Seedream 4.0】古诗词鉴赏新版', '视频生成', '', '', 'Workflow-gushici_jianshang_1-draft-4862', 53),
  ('曼波推书', 'hbts_1', '【更新Seedream 4.0】曼波推书', '其他', '', '', 'Workflow-hbts_1-draft-5767', 54),
  ('火柴人心理学白竖版3:4', 'hcrxlxbai_3_4_1', '【更新Seedream 4.0】火柴人心理学白竖版3:4', '教育工具', '', '', 'Workflow-hcrxlxbai_3_4_1-draft-4803', 55),
  ('火柴人心理学黑竖版3:4', 'hcrxlxhei_3_4_1', '【更新Seedream 4.0】火柴人心理学黑竖版3:4', '教育工具', '', '', 'Workflow-hcrxlxhei_3_4_1-draft-4781', 56),
  ('半写实风格的数字插画推文', 'history_people_v2_1', '半写实风格的数字插画推文', '其他', '', '', 'Workflow-history_people_V2_1-draft-5123', 57),
  ('动态-写实视频工作流，一个视频几千资源点', 'history_people_story_v11_1', '【更新Seedream 4.0】动态-写实视频工作流，一个视频几千资源点', '视频生成', '', '', 'Workflow-history_people_story_V11_1-draft-5502', 58),
  ('微观视频-文案自定义版 一个视频几千资源点', 'history_people_story_v12_1', '【更新Seedream 4.0】微观视频-文案自定义版 一个视频几千资源点', '视频生成', '', '', 'Workflow-history_people_story_V12_1-draft-5111', 59),
  ('竖版故事V2', 'history_people_story_shubanv2_1', '【更新Seedream 4.0】竖版故事V2', '视频生成', '', '', 'Workflow-history_people_story_shubanv2_1-draft-4841', 60),
  ('新闻播报写实工作流', 'history_people_story_v10_1', '【更新Seedream 4.0】新闻播报写实工作流', '视频生成', '', '', 'Workflow-history_people_story_v10_1-draft-2732', 61),
  ('新闻播报写实工作流', 'history_people_story_v10_1-2', '【更新Seedream 4.0】新闻播报写实工作流', '视频生成', '', '', 'Workflow-history_people_story_v10_1-draft-5486', 62),
  ('爆款短剧故事插画版视频（有开头版）', 'history_people_story_v3_1', '【更新Seedream 4.0】爆款短剧故事插画版视频（有开头版）', '视频生成', '', '', 'Workflow-history_people_story_v3_1-draft-5824', 63),
  ('像素风推文竖版', 'history_people_story_v9_1', '【更新Seedream 4.0】像素风推文竖版', '其他', '', '', 'Workflow-history_people_story_v9_1-draft-5643', 64),
  ('海林爱读书工作流', 'hlads_1', '海林爱读书工作流', '其他', '', '', 'Workflow-hlads_1-draft-4578', 65),
  ('猴子打工 工作流-动态视频一个视频几千资源点', 'houzidagong_1', '【更新Seedream 4.0】猴子打工 工作流-动态视频一个视频几千资源点', '视频生成', '', '', 'Workflow-houzidagong_1-draft-5322', 66),
  ('一键换装', 'huan_yifu_1_1', '一键换装', '其他', '', '', 'Workflow-huan_yifu_1_1-draft-5334', 67),
  ('回答我视频', 'huidawo_1', '【更新Seedream 4.0】回答我视频', '视频生成', '', '', 'Workflow-huidawo_1-draft-6251', 68),
  ('动态火柴人--需要几千资源点', 'huochairen_v1_1', '【更新Seedream 4.0】动态火柴人--需要几千资源点', '其他', '', '', 'Workflow-huochairen_v1_1-draft-5013', 69),
  ('简笔画励志工作流', 'jianbi_lizhi_video_1', '【更新Seedream 4.0】简笔画励志工作流', '其他', '', '', 'Workflow-jianbi_lizhi_video_1-draft-5423', 70),
  ('简笔书单4.0', 'jianbishudan_4_0_1', '【更新Seedream 4.0】简笔书单4.0', '视频生成', '', '', 'Workflow-jianbishudan_4_0_1-draft-4904', 71),
  ('生成在线简历', 'jianli_1', '【更新Seedream 4.0】生成在线简历', '其他', '', '', 'Workflow-jianli_1-draft-6308', 72),
  ('学习方法规划师，一键生成教育视频', 'jiaoyuguihua_1', '【更新Seedream 4.0】学习方法规划师，一键生成教育视频', '视频生成', '', '', 'Workflow-jiaoyuguihua_1-draft-6094', 73),
  ('假如书籍会说话', 'jiarushujihuishuohua_1', '【更新Seedream 4.0】假如书籍会说话', '其他', '', '', 'Workflow-jiarushujihuishuohua_1-draft-6159', 74),
  ('【6.5优化版】书单类-家庭育儿教育对话版', 'jiatingyuerjiaoyuduihuaban_3_1', '【更新Seedream 4.0】【6.5优化版】书单类-家庭育儿教育对话版', '视频生成', '', '', 'Workflow-jiatingyuerjiaoyuduihuaban_3_1-draft-5990', 75),
  ('今日头条输入主题自动生成图文', 'jinritoutiaotw_1', '今日头条输入主题自动生成图文', '图文生成', '', '', 'Workflow-jinritoutiaotw_1-draft-6797', 76),
  ('生成金融知识视频工作流', 'jinrongzhishi_case_video_1', '生成金融知识视频工作流', '视频生成', '', '', 'Workflow-jinrongzhishi_case_video_1-draft-7137', 77),
  ('家庭教育凯斯・哈林风格-动态  -一个视频几千资源点', 'jtjiaoyu_dongtai_glfg_1', '【更新Seedream 4.0】家庭教育凯斯・哈林风格-动态  -一个视频几千资源点', '视频生成', '', '', 'Workflow-jtjiaoyu_dongtai_glfg_1-draft-5194', 78),
  ('家庭教育人物对话-高配版', 'jtjy_duihua_1_1', '【更新Seedream 4.0】家庭教育人物对话-高配版', '教育工具', '', '', 'Workflow-jtjy_duihua_1_1-draft-5212', 79),
  ('家庭教育人物对话-高配版', 'jtjy_duihua_1_1-2', '【更新Seedream 4.0】家庭教育人物对话-高配版', '教育工具', '', '', 'Workflow-jtjy_duihua_1_1-draft-5226', 80),
  ('克隆声音 | Index-TTS 官方版', 'kelongsy_1', '克隆声音 | Index-TTS 官方版', '其他', '', '', 'Workflow-kelongsy_1-draft-4185', 81),
  ('老黄历没有日历播报', 'laohuangli_2_1', '【更新Seedream 4.0】老黄历没有日历播报', '视频生成', '', '', 'Workflow-laohuangli_2_1-draft-6116', 82),
  ('儿童多角色故事高阶版(最新版)-竖版', 'lh_child_story_1_1', '【更新Seedream 4.0】儿童多角色故事高阶版(最新版)-竖版', '视频生成', '', '', 'Workflow-lh_child_story_1_1-draft-4989', 83),
  ('猫咪拟人视频', 'maomi_niren_1', '【更新Seedream 4.0】猫咪拟人视频', '视频生成', '', '', 'Workflow-maomi_niren_1-draft-5523', 84),
  ('毛选开头爆款书单', 'maoxuan_shudan_1', '【更新Seedream 4.0】毛选开头爆款书单', '视频生成', '', '', 'Workflow-maoxuan_shudan_1-draft-4711', 85),
  ('一键生成情感语录', 'mb_yl_1_1', '一键生成情感语录', '视频生成', '', '', 'Workflow-mb_yl_1_1-draft-4536', 86),
  ('萌宠视频工作流', 'mengchongpiliang_1', '萌宠视频工作流', '视频生成', '', '', 'Workflow-mengchongpiliang_1-draft-5366', 87),
  ('每天认识一辆车', 'mtrscar_video_1_jike', '每天认识一辆车', '其他', '', '', 'Workflow-mtrscar_video_1_jike-draft-6668', 88),
  ('每天听懂一首歌', 'music_everday_1', '每天听懂一首歌', '其他', '', '', 'Workflow-music_everday_1-draft-4348', 89),
  ('品味人生爆火书单视频  3:4', 'pwrs_shudan_1', '【更新Seedream 4.0】品味人生爆火书单视频  3:4', '视频生成', '', '', 'Workflow-pwrs_shudan_1-draft-4623', 90),
  ('品味人生爆火书单视频  3:4', 'pwrs_shudan_1-2', '【更新Seedream 4.0】品味人生爆火书单视频  3:4', '视频生成', '', '', 'Workflow-pwrs_shudan_1-draft-9755', 91),
  ('30分钟铅笔风读书工作流', 'qianbifeng30_1', '30分钟铅笔风读书工作流', '其他', '', '', 'Workflow-qianbifeng30_1-draft-4554', 92),
  ('情感视频，自定义版本', 'qinggan_zidingyi_1', '【更新Seedream 4.0】情感视频，自定义版本', '视频生成', '', '', 'Workflow-qinggan_zidingyi_1-draft-4940', 93),
  ('清新感推书工作流', 'qinxingan_shudan_1', '【更新Seedream 4.0】清新感推书工作流', '其他', '', '', 'Workflow-qinxingan_shudan_1-draft-4883', 94),
  ('启蒙早教故事', 'qm_yehb_1', '【更新Seedream 4.0】启蒙早教故事', '视频生成', '', '', 'Workflow-qm_yehb_1-draft-4743', 95),
  ('全类型视频生成-高度自定义，动态视频/静态插画讲解-动态视频资源消耗巨大', 'quanleixingshipin_1', '【更新Seedream 4.0】全类型视频生成-高度自定义，动态视频/静态插画讲解-动态视频资源消耗巨大', '视频生成', '', '', 'Workflow-quanleixingshipin_1-draft-4638', 96),
  ('全行业获客,培训,工作流', 'qxyhk_1', '【更新Seedream 4.0】全行业获客,培训,工作流', '其他', '', '', 'Workflow-qxyhk_1-draft-4599', 97),
  ('佛系养生工作流', 'red_book_health_v2_1', '【更新Seedream 4.0】佛系养生工作流', '教育工具', '', '', 'Workflow-red_book_health_v2_1-draft-5442', 98),
  ('做个狠人, 认知觉醒工作流，分镜优化版本 ', 'rzjx_v1_2_1', '【更新Seedream 4.0】做个狠人, 认知觉醒工作流，分镜优化版本 ', '其他', '', '', 'Workflow-rzjx_v1_2_1-draft-5705', 99),
  ('商业说工作流', 'shangye_v2_1', '商业说工作流', '其他', '', '', 'Workflow-shangye_v2_1-draft-5095', 100),
  ('认知视频｜深度进化Theo', 'shendujinhua_1', '认知视频｜深度进化Theo', '视频生成', '', '', 'Workflow-shendujinhua_1-draft-3955', 101),
  ('神话人物的一生一镜到底', 'shenghuayisheng_1', '神话人物的一生一镜到底', '视频生成', '', '', 'Workflow-shenghuayisheng_1-draft-4500', 102),
  ('翻书效果书单', 'shudan_fanshu_1', '【更新Seedream 4.0】翻书效果书单', '视频生成', '', '', 'Workflow-shudan_fanshu_1-draft-6137', 103),
  ('旋转开场书单', 'shudan_v8_1', '旋转开场书单', '视频生成', '', '', 'Workflow-shudan_v8_1-draft-4388', 104),
  ('水獭日常生活工作流-动态视频一个视频几千资源点', 'shuita_richang_1', '水獭日常生活工作流-动态视频一个视频几千资源点', '视频生成', '', '', 'Workflow-shuita_richang_1-draft-5147', 105),
  ('数字人-图片-infinite 【720P+高清+声音】', 'shuziren_infinite_1', '数字人-图片-infinite 【720P+高清+声音】', '图文生成', '', '', 'Workflow-shuziren_infinite_1-draft-4145', 106),
  ('sora2直播带货视频', 'sora2_yingxiaosp_v2_1', 'sora2直播带货视频', '视频生成', '', '', 'Workflow-sora2_yingxiaoSP_V2_1-draft-4256', 107),
  ('睡前一本书。', 'sqybs_douyin_2_1', '睡前一本书。', '其他', '', '', 'Workflow-sqybs_douyin_2_1-draft-4082', 108),
  ('听故事学历史', 'story_v2_1', '听故事学历史', '视频生成', '', '', 'Workflow-story_V2_1-draft-4367', 109),
  ('成语故事动态-一个视频几千资源点', 'story_flow_v1_1', '成语故事动态-一个视频几千资源点', '视频生成', '', '', 'Workflow-story_flow_v1_1-draft-4204', 110),
  ('民间故事_V5', 'story_minjian_v5_1', '民间故事_V5', '视频生成', '', '', 'Workflow-story_minjian_V5_1-draft-4456', 111),
  ('油画版故事工作流', 'story_youhua_1', '油画版故事工作流', '视频生成', '', '', 'Workflow-story_youhua_1-draft-4227', 112),
  ('听故事学中药', 'story_zhongyao_1', '听故事学中药', '视频生成', '', '', 'Workflow-story_zhongyao_1-draft-4478', 113),
  ('天涯神帖-文案自定义版', 'tianyashenti_1', '天涯神帖-文案自定义版', '图文生成', '', '', 'Workflow-tianyashenti_1-draft-5542', 114),
  ('田园生活治愈工作流', 'tianyuan_gushi_huaijiu_1', '【更新Seedream 4.0】田园生活治愈工作流', '其他', '', '', 'Workflow-tianyuan_gushi_huaijiu_1-draft-5659', 115),
  ('短视频文案提取+分析+批量改写+写入飞书【免费插件版】', 'video2text_feishu_1', '短视频文案提取+分析+批量改写+写入飞书【免费插件版】', '视频生成', '', '', 'Workflow-video2text_feishu_1-draft-5614', 116),
  ('视频混剪', 'video_oss_create_023251', '视频混剪', '视频生成', '', '', 'Workflow-video_oss_create_023251-draft-4542', 117),
  ('视频 | 认知思维提升', 'video_stick_psy_cn_v3_1', '【更新Seedream 4.0】视频 | 认知思维提升', '视频生成', '', '', 'Workflow-video_stick_psy_cn_v3_1-draft-5886', 118),
  ('一键生成文言文视频', 'wenyanwen_1', '【更新Seedream 4.0】一键生成文言文视频', '视频生成', '', '', 'Workflow-wenyanwen_1-draft-5679', 119),
  ('作业批改_学生', 'work_correction_stu_three_1', '作业批改_学生', '其他', '', '', 'Workflow-work_correction_stu_three_1-draft-9144', 120),
  ('汇总 4 个审核环节的结果，生成 Markdown 格式报告，转换为 Word 文档。', 'workflow_generate_report', '汇总 4 个审核环节的结果，生成 Markdown 格式报告，转换为 Word 文档。', '其他', '', '', 'Workflow-workflow_generate_report-draft-7121', 121),
  ('签字完整性审核', 'workflow_image_review', '签字完整性审核', '其他', '', '', 'Workflow-workflow_image_review-draft-7106', 122),
  ('直播合规审核工作流', 'workflow_live_compliance', '直播合规审核工作流', '其他', '', '', 'Workflow-workflow_live_compliance-draft-7114', 123),
  ('数量比对审核 ', 'workflow_quantity_check', '数量比对审核 ', '其他', '', '', 'Workflow-workflow_quantity_check-draft-7095', 124),
  ('数量比对审核 ', 'workflow_quantity_check-2', '数量比对审核 ', '其他', '', '', 'Workflow-workflow_quantity_check-draft-7729', 125),
  ('我是宝宝  视频大概6000资源点             ', 'woshibaobao_1', '【更新Seedream 4.0】我是宝宝  视频大概6000资源点             ', '视频生成', '', '', 'Workflow-woshibaobao_1-draft-4763', 126),
  ('写入学生的作业情况', 'write_stu_work_three_1', '写入学生的作业情况', '其他', '', '', 'Workflow-write_stu_work_three_1-draft-9139', 127),
  ('根据小红书主页获取小红书用户笔记', 'xhs_get_user_note', '根据小红书主页获取小红书用户笔记', '图文生成', '', '', 'Workflow-xhs_get_user_note-draft-9541', 128),
  ('小说推文横版漫画风格自定义文案', 'xiaoshuotuiwen_1', '【更新Seedream 4.0】小说推文横版漫画风格自定义文案', '图文生成', '', '', 'Workflow-xiaoshuotuiwen_1-draft-5629', 129),
  ('心理学对标账号sdic心理', 'xinli_sdic_1', '【更新Seedream 4.0】心理学对标账号sdic心理', '教育工具', '', '', 'Workflow-xinli_sdic_1-draft-4689', 130),
  ('心理学火柴人带封面+开场特写+图片重试', 'xinlixue_huochairentx_v2_1', '【更新Seedream 4.0】心理学火柴人带封面+开场特写+图片重试', '图文生成', '', '', 'Workflow-xinlixue_huochairentx_V2_1-draft-5949', 131),
  ('心理工作流思维导图', 'xinlixue_siweidaotu_1', '【更新Seedream 4.0】心理工作流思维导图', '教育工具', '', '', 'Workflow-xinlixue_siweidaotu_1-draft-5177', 132),
  ('心理学火柴人最新版本', 'xinlixue_v4_1_1', '心理学火柴人最新版本', '教育工具', '', '', 'Workflow-xinlixue_v4_1_1-draft-4325', 133),
  ('新闻对话-孙子兵法版本', 'xinwen_sunzibingfa_1', '新闻对话-孙子兵法版本', '其他', '', '', 'Workflow-xinwen_sunzibingfa_1-draft-5351', 134),
  ('一键生成星座治愈短视频', 'xinzuozhiyu_1', '【更新Seedream 4.0】一键生成星座治愈短视频', '视频生成', '', '', 'Workflow-xinzuozhiyu_1-draft-6051', 135),
  ('心态变强工作流【全赛道｜封面帧｜改背景语录】', 'xtbq_1', '心态变强工作流【全赛道｜封面帧｜改背景语录】', '视频生成', '', '', 'Workflow-xtbq_1-draft-4436', 136),
  ('TK悬疑小说英文', 'xuanyi_2_1_1', '【更新Seedream 4.0】TK悬疑小说英文', '其他', '', '', 'Workflow-xuanyi_2_1_1-draft-4655', 137),
  ('悬疑小说中文', 'xuanyi_3_1', '【更新Seedream 4.0】悬疑小说中文', '其他', '', '', 'Workflow-xuanyi_3_1-draft-4728', 138),
  ('心眼子教学黑白火柴人', 'xyz_hei_hcr_1', '【更新Seedream 4.0】心眼子教学黑白火柴人', '其他', '', '', 'Workflow-xyz_hei_hcr_1-draft-5289', 139),
  ('绿色健康养生', 'yangsheng_tuwen_1', '【更新Seedream 4.0】绿色健康养生', '教育工具', '', '', 'Workflow-yangsheng_tuwen_1-draft-5465', 140),
  ('每天认识一种药草科普视频-静态版', 'yaocao_sp_tuwen_1', '【更新Seedream 4.0】每天认识一种药草科普视频-静态版', '视频生成', '', '', 'Workflow-yaocao_sp_tuwen_1-draft-5068', 141),
  ('每天认识一种药草科普视频-静态版', 'yaocao_sp_tuwen_1-2', '【更新Seedream 4.0】每天认识一种药草科普视频-静态版', '视频生成', '', '', 'Workflow-yaocao_sp_tuwen_1-draft-5081', 142),
  ('医疗爆款二改主流程', 'yiliao', '医疗爆款二改主流程', '其他', '', '', 'Workflow-yiliao-draft-6400', 143),
  ('医疗爆款二改主流程', 'yiliao-2', '医疗爆款二改主流程', '其他', '', '', 'Workflow-yiliao-draft-7182', 144),
  ('谐音梗英语', 'yingyu_xieyingeng_1', '【更新Seedream 4.0】谐音梗英语', '教育工具', '', '', 'Workflow-yingyu_xieyingeng_1-draft-5382', 145),
  ('此工作流专为分析幼儿在园日的表现而设计。当家长或教师希望获取某个孩子当日或近期的情绪状态、活动参与情况、社交互动亮点以及基于这些观察的家园共育建议时，应调用此工作流。其核心目标是基于图像、文本记录等数据，生成一份温暖、专业且可执行的成长报告，促进家园之间的信息同步与共育协作。', 'youji', '此工作流专为分析幼儿在园日的表现而设计。当家长或教师希望获取某个孩子当日或近期的情绪状态、活动参与情况、社交互动亮点以及基于这些观察的家园共育建议时，应调用此工作流。其核心目标是基于图像、文本记录等数据，生成一份温暖、专业且可执行的成长报告，促进家园之间的信息同步与共育协作。', 'AI工具', '', '', 'Workflow-youji-draft-1142', 146),
  ('一键生成鱼书书书治愈短视频', 'ysss_douyin_1', '一键生成鱼书书书治愈短视频', '视频生成', '', '', 'Workflow-ysss_douyin_1-draft-4521', 147),
  ('育儿经验教育V2', 'yuer_v2_1', '【更新Seedream 4.0】育儿经验教育V2', '教育工具', '', '', 'Workflow-yuer_V2_1-draft-5306', 148),
  ('语录赛道：情感、创业、认知等等', 'yulu_2', '语录赛道：情感、创业、认知等等', '视频生成', '', '', 'Workflow-yulu_2-draft-3532', 149),
  ('哲学视频', 'zhexueshipin_1', '【更新Seedream 4.0】哲学视频', '视频生成', '', '', 'Workflow-zhexueshipin_1-draft-6225', 150),
  ('治愈小女孩', 'zhiyuxiaonvhai_1', '【更新Seedream 4.0】治愈小女孩', '其他', '', '', 'Workflow-zhiyuxiaonvhai_1-draft-5403', 151);